[package]
name = "ferilous_fluids"
version = "0.1.0"
edition = "2021"

authors = ["alberse.john@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7"
glam = { version = "0.8.6", features = ["mint"] }
